### ISSUE TITLE
Allow to upload custom cubes

### ISSUE THREAD

**Issue by jgabrielygalan** [jgabrielygalan/sotiny#13]
Think of a way to upload custom cubes. Issues: 
- How to upload the file
- How to identify cubes

**Comment by silasary** [comment]
Best way is probably just use the CubeCobra API?

**Comment by jgabrielygalan** [comment]
Good idea. I'll look into it

**Comment by jgabrielygalan** [comment]
In order to properly manage custom cubes, we might need to rethink the interaction with the players. Maybe we should add a command to start a draft passing that id:
>create <id>
that creates an empty draft with that cubelist. Then modify the "play" command so that you can join an existing draft (another command for listing "waiting" drafts).

**Comment by jgabrielygalan** [comment]
@silasary we went for a simple solution, in the start command you can pass the CubeCobra id and it will download the list. Thanks for the suggestion.
