### ISSUE TITLE
Validate inputs

### ISSUE THREAD

**Issue by silasary** [jgabrielygalan/sotiny#26]
- [x] Packs of zero still contain one card. You shouldn't be able to make a pack of zero. 

- [x] Zero packs softlocks the draft. You shouldn't be able to draft with zero packs

The above is probably also true of all negative numbers

I'm a terrible person

**Comment by jgabrielygalan** [comment]
yes, input validation is needed. Thanks for the feedback.

**Comment by jgabrielygalan** [comment]
Fixed by 011890ae967583130bbba6f669d8fd7c414d3a54
