### ISSUE TITLE
Support some kind of persistence

### ISSUE THREAD

**Issue by jgabrielygalan** [jgabrielygalan/sotiny#32]
To be able to restart the bot without losing running drafts, we should persist the running drafts somewhere (pickle? a database?)

**Comment by silasary** [comment]
Redis?

**Comment by jgabrielygalan** [comment]
could be an option. I want to explore the pickle library first, so as to not require an additional component, but Redis is definitely an option.

**Comment by jgabrielygalan** [comment]
Turns out that the Discord API objects (Member, User, Message) cannot be serialized, so we don't have a real advantage using a serialization library. 
The task then is to store the IDs of things in our state (User.id, Member.id, Message.id) and then be able to recreate the objects using discords functions to get them by id. So a little bit more work.

**Comment by silasary** [comment]
You don't want to be using pickle for storing data between versions.
It breaks hard if a class/field gets removed/renamed

**Comment by silasary** [comment]
Done
