### ISSUE TITLE
Support several drafts in parallel per guild 

### ISSUE THREAD

**Issue by jgabrielygalan** [jgabrielygalan/sotiny#47]
Right now we only support one running draft per guild. Support several. Think about the implications to the draft creation or start interface, so that the commands don't end up being too cryptic and difficult to use.

**Comment by jgabrielygalan** [comment]
One simple option to have something working is the following:
- Have a list of running drafts.
- Have a single "to start" draft.

The play/cancel commands work on the "to start" draft. The start command moves that draft to the "running" list and creates an empty slot for the "to start" draft.

Caveats: 

- a player cannot play in 2 drafts unless we complicate the picks and pack commands. Those 

- commands need to be changed to find the user in the list of running drafts.

**Comment by silasary** [comment]
I would do similar, but also add a check to ensure that if a player is in any of the "running" drafts, they cannot enter the pending one.

What this means:

* DM commands don't need to be made more complicated-  Just find the singular draft the player is in, and act on it.
* >pending will only work for drafters, not for other people in the channel.

**Comment by jgabrielygalan** [comment]
Currently the DM commands (pick, pack and pending) don't work correctly. A user can be playing drafts at two different guilds, and those commands are working on the first draft found in the dict. So, they need to be fixed: https://github.com/jgabrielygalan/sotiny/issues/43
I agree on limiting a single running draft per player per guild. So we'll try it that way.

**Comment by jgabrielygalan** [comment]
Since in Penny Dreadful we are having long running drafts, it's desirable that a player can play in two or more drafts at the same time in the same guild. So we should think a solution to interact with these drafts in the private commands (for example: add a unique id to each draft and use that to disambiguate the command)
